# Generated by Django 5.0.7 on 2024-11-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_assignment_assignmentsubmission_courseresource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_file',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
