# Generated by Django 5.0.6 on 2024-10-03 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cno', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('course_class', models.CharField(max_length=2)),
                ('cname', models.CharField(max_length=20)),
                ('cintro', models.CharField(max_length=500)),
                ('coutline', models.CharField(max_length=100)),
                ('calender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('smail', models.CharField(max_length=13)),
                ('sconcern', models.IntegerField(max_length=500)),
                ('sfans', models.IntegerField(max_length=500)),
                ('sfavor', models.IntegerField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tno', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=20)),
                ('tmail', models.CharField(max_length=13)),
                ('toffice', models.CharField(max_length=10)),
                ('tphone', models.CharField(max_length=15)),
                ('tintro', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ChooseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccgrade', models.IntegerField(max_length=100)),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.course')),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='tno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.teacher'),
        ),
    ]
