# Generated by Django 5.0.6 on 2024-10-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_chooseclass_ccgrade_alter_student_sconcern_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='smail',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tmail',
            field=models.CharField(max_length=30),
        ),
    ]
