# Generated by Django 5.0.6 on 2024-10-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_student_smail_alter_teacher_tmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_no',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
