# Generated by Django 5.0.6 on 2024-10-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_course_course_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='picAddr',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
