# Generated by Django 5.1.1 on 2024-11-05 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0005_course_picaddr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="sno",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="CourseMessage",
            fields=[
                ("mno", models.AutoField(primary_key=True, serialize=False)),
                ("mtime", models.DateTimeField(auto_now_add=True)),
                ("mtitle", models.CharField(max_length=100)),
                ("minfo", models.TextField()),
                (
                    "mcourse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.course",
                    ),
                ),
                (
                    "msend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseMessageStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                (
                    "cno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.course",
                    ),
                ),
                (
                    "mno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.coursemessage",
                    ),
                ),
                (
                    "sno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.student",
                    ),
                ),
            ],
        ),
    ]
