# Generated by Django 5.1.1 on 2024-11-14 15:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0006_alter_student_sno_coursemessage_coursemessagestatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "assignment_file",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("due_date", models.DateTimeField()),
                ("isMutualAssessment", models.BooleanField(default=False)),
                ("allowDelaySubmission", models.BooleanField(default=False)),
                ("delay_date", models.DateField(blank=True, default=None, null=True)),
                (
                    "maxGrade",
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_text", models.TextField(blank=True, null=True)),
                (
                    "submission_file",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delay_time",
                    models.IntegerField(
                        default=None,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.assignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseResource",
            fields=[
                ("rno", models.AutoField(primary_key=True, serialize=False)),
                ("rname", models.CharField(max_length=100)),
                ("rdesc", models.CharField(blank=True, max_length=500, null=True)),
                ("rfile", models.CharField(max_length=200)),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                (
                    "cname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResourceProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("progress", models.CharField(max_length=100)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.courseresource",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.student",
                    ),
                ),
            ],
        ),
    ]
