# Generated by Django 5.1.1 on 2024-11-16 22:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0007_assignment_assignmentsubmission_courseresource_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folder_name", models.CharField(max_length=100)),
                (
                    "folder_desc",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assignment",
            name="start_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="mutual_assessments_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="delay_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name="CourseResource_test",
            fields=[
                (
                    "rno",
                    models.AutoField(max_length=10, primary_key=True, serialize=False),
                ),
                ("rname", models.CharField(max_length=100)),
                ("rdesc", models.CharField(blank=True, max_length=500, null=True)),
                ("rfile", models.CharField(max_length=200)),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                (
                    "cname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.course",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="homepage.folder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseResource_ppt",
            fields=[
                (
                    "rno",
                    models.AutoField(max_length=10, primary_key=True, serialize=False),
                ),
                ("rname", models.CharField(max_length=100)),
                ("rdesc", models.CharField(blank=True, max_length=500, null=True)),
                ("rfile", models.CharField(max_length=200)),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                (
                    "cname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.course",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="homepage.folder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single_choice", "单选题"),
                            ("multiple_choice", "多选题"),
                            ("subjective", "主观题"),
                        ],
                        default="single_choice",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("easy", "简单"), ("medium", "中等"), ("hard", "困难")],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("knowledge_point", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("options", models.JSONField(blank=True, null=True)),
                (
                    "correct_answer",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("answer_explanation", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="homepage.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MutualAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("feedback", models.TextField(blank=True, null=True)),
                ("assessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.assignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.student",
                    ),
                ),
                (
                    "to_assess_student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="homepage.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("assignment", "student", "to_assess_student")},
            },
        ),
    ]
