# Generated by Django 5.1.1 on 2024-11-17 21:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0008_folder_assignment_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="delay_grade",
            field=models.IntegerField(
                default=-1,
                validators=[
                    django.core.validators.MinValueValidator(-1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="mutualassessment",
            name="is_assessed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="grade",
            field=models.IntegerField(
                default=-1,
                validators=[
                    django.core.validators.MinValueValidator(-1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.CreateModel(
            name="TeacherAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("feedback", models.TextField(blank=True, null=True)),
                ("assessed_at", models.DateTimeField(auto_now_add=True)),
                ("showFeedback", models.BooleanField(default=False)),
                (
                    "AssignmentSubmission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.assignmentsubmission",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.assignment",
                    ),
                ),
            ],
        ),
    ]
