# Generated by Django 5.1.1 on 2024-11-19 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0009_assignmentsubmission_delay_grade_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="resourceprogress", name="resource",),
        migrations.RemoveField(model_name="resourceprogress", name="student",),
        migrations.RenameField(
            model_name="courseresource_ppt", old_name="rfile", new_name="rfileInOSS",
        ),
        migrations.RemoveField(model_name="courseresource_ppt", name="folder",),
        migrations.RemoveField(model_name="courseresource_ppt", name="rdesc",),
        migrations.RemoveField(model_name="folder", name="folder_desc",),
        migrations.AddField(
            model_name="courseresource_ppt",
            name="rfileInSql",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="homepage.folder",
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="cno",
            field=models.ForeignKey(
                default="0001",
                on_delete=django.db.models.deletion.CASCADE,
                to="homepage.course",
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="folderPathInSql",
            field=models.CharField(
                blank=True, default="NULL", max_length=500, null=True
            ),
        ),
        migrations.DeleteModel(name="CourseResource",),
        migrations.DeleteModel(name="ResourceProgress",),
    ]
