# Generated by Django 5.1.1 on 2024-11-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0010_remove_resourceprogress_resource_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="isPostMutualAssessment",
            field=models.BooleanField(default=False),
        ),
    ]
