# Generated by Django 5.1.1 on 2024-10-09 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0005_course_picaddr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('dno', models.IntegerField(primary_key=True, serialize=False)),
                ('dtitle', models.TextField()),
                ('dinfo', models.TextField()),
                ('postTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
                ('havePic', models.BooleanField(default=False)),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.course')),
                ('ownerNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rno', models.IntegerField(primary_key=True, serialize=False)),
                ('rinfo', models.TextField()),
                ('postTime', models.DateTimeField(auto_now_add=True)),
                ('likeNum', models.IntegerField(default=0)),
                ('havePic', models.BooleanField(default=False)),
                ('isTop', models.BooleanField(default=False)),
                ('dno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatRoom.discussion')),
                ('ownerNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
