# Generated by Django 5.1.1 on 2024-11-08 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("homepage", "0006_alter_student_sno_coursemessage_coursemessagestatus"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Discussion",
            fields=[
                ("dno", models.AutoField(primary_key=True, serialize=False)),
                ("dtitle", models.TextField()),
                ("dinfo", models.TextField()),
                ("postTime", models.DateTimeField(auto_now_add=True)),
                ("updateTime", models.DateTimeField(auto_now=True)),
                ("havePic", models.BooleanField(default=False)),
                ("like", models.IntegerField(default=0)),
                (
                    "cno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.course",
                    ),
                ),
                (
                    "ownerNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiscussionLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatRoom.discussion",
                    ),
                ),
                (
                    "userNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavoritesFolder",
            fields=[
                ("fno", models.AutoField(primary_key=True, serialize=False)),
                ("fname", models.CharField(max_length=50)),
                ("fstatus", models.BooleanField(default=False)),
                (
                    "userNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatRoom.discussion",
                    ),
                ),
                (
                    "fno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatRoom.favoritesfolder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PictureDisscussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pfile", models.FileField(upload_to="pictures")),
                (
                    "dno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatRoom.discussion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("rno", models.AutoField(primary_key=True, serialize=False)),
                ("rinfo", models.TextField()),
                ("postTime", models.DateTimeField(auto_now_add=True)),
                ("likeNum", models.IntegerField(default=0)),
                ("havePic", models.BooleanField(default=False)),
                ("isTop", models.BooleanField(default=False)),
                (
                    "dno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatRoom.discussion",
                    ),
                ),
                (
                    "ownerNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PictureReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pfile", models.FileField(upload_to="pictures")),
                (
                    "rno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatRoom.review",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "userNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatRoom.review",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="atMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sendTime", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=False)),
                (
                    "receiverno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "senderno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatRoom.review",
                    ),
                ),
            ],
        ),
    ]
