# Generated by Django 5.1.1 on 2024-11-05 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatRoom", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussion",
            name="dno",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="review",
            name="rno",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatRoom.discussion",
                    ),
                ),
                (
                    "userNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatRoom.review",
                    ),
                ),
                (
                    "userNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PictureDisscussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pfile", models.FileField(upload_to="pictures")),
                (
                    "dno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatRoom.discussion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PictureReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pfile", models.FileField(upload_to="pictures")),
                (
                    "rno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatRoom.review",
                    ),
                ),
            ],
        ),
    ]
