# Generated by Django 5.1.1 on 2024-11-12 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatRoom", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("tno", models.AutoField(primary_key=True, serialize=False)),
                ("tname", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="FavoritesFolderOfOthers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatRoom.favoritesfolder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiscussionWithTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatRoom.discussion",
                    ),
                ),
                (
                    "tno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chatRoom.topic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "followed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("fan", "followed")},},
        ),
    ]
