# Generated by Django 5.1.1 on 2024-11-17 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatRoom", "0002_topic_favoritesfolderofothers_discussionwithtopic_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="favoritesfolder",
            name="likeNum",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="FavoritesFolderLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatRoom.favoritesfolder",
                    ),
                ),
                (
                    "userNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
